# Generated by Django 4.2.24 on 2025-10-05 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lesson_options_lesson_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='topic',
            name='background_color',
            field=models.CharField(choices=[('#E53E3E', 'Red'), ('#DD6B20', 'Orange'), ('#38A169', 'Green'), ('#805AD5', 'Purple'), ('#3182CE', 'Blue'), ('#319795', 'Teal')], default='#38A169', max_length=7),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='fas fa-leaf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(default='fas fa-leaf', help_text='FontAwesome icon class (e.g., fas fa-thermometer-half)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.topic'),
        ),
    ]
