# Generated by Django 5.2.7 on 2025-10-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_topic_options_topic_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='points',
        ),
        migrations.AddField(
            model_name='course',
            name='completion_points',
            field=models.PositiveIntegerField(default=150, help_text='Points awarded for completing this course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='points_value',
            field=models.PositiveIntegerField(default=25, help_text='Points awarded for completing this lesson'),
        ),
    ]
