# Generated by Django 5.2.7 on 2025-11-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_certificate_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='requires_video_watch',
            field=models.BooleanField(default=True, help_text='User must watch full video to complete lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when video was fully watched', null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_watch_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of video watched (0-100)'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_watched',
            field=models.BooleanField(default=False, help_text='Video has been fully watched'),
        ),
    ]
