# Generated by Django 5.2.7 on 2025-11-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lesson_requires_video_watch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='requires_video_watch',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='video_completed_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='video_watch_percentage',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='video_watched',
        ),
    ]
