# Generated by Django 4.2.30 on 2026-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_lesson_requires_video_watch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this lesson', null=True, upload_to='lessons/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload a PDF file for this lesson', null=True, upload_to='lessons/pdfs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('pdf', 'PDF'), ('image', 'Image'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('practical', 'Practical')], default='text', max_length=20),
        ),
    ]
