# Generated by Django 4.2.30 on 2026-04-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lesson_image_lesson_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson_watched',
            field=models.BooleanField(default=False, help_text='Lesson content fully consumed'),
        ),
    ]
