# Generated by Django 5.2.7 on 2025-10-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_badge_courses_required_badge_quizzes_passed_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='last_login_bonus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
