# Generated by Django 5.2.7 on 2025-10-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_userprogress_last_login_bonus_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='xp',
        ),
    ]
