# Generated by Django 5.2.7 on 2025-11-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_remove_userprogress_level_remove_userprogress_xp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name_plural': 'User Progress'},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='challenge_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='challenges_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='userprogress',
            table='user_progress',
        ),
    ]
