# Generated by Django 5.2.7 on 2025-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_question_quizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='bulk_questions_json',
            field=models.TextField(blank=True, help_text='Paste JSON to bulk add questions. Leave empty if adding questions individually.', null=True),
        ),
    ]
