# Generated by Django 5.2.7 on 2025-10-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_question_points_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
