# Generated by Django 4.2.30 on 2026-04-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='scheduled_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='scheduled_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
