# Generated by Django 4.2.29 on 2026-04-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teachernotification_is_archived_studentnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachernotification',
            name='event_type',
            field=models.CharField(choices=[('course_enrollment', 'Course Enrollment'), ('quiz_completed', 'Quiz Completed'), ('course_completed', 'Course Completed'), ('challenge_submitted', 'Challenge Submitted')], max_length=30),
        ),
    ]
